### ISSUE TITLE
`req.connection` is deprecated

### ISSUE THREAD

**Issue by silverwind** [jshttp/forwarded#8]
`req.connection` is [deprecated](https://nodejs.org/api/http.html#http_request_connection) since Node 13.0.0. [`req.socket`](https://nodejs.org/api/http.html#http_request_socket) should be used instead (it's available since Node 0.3.0).

https://github.com/jshttp/forwarded/blob/eb75571c7a3afdbb04a435411c91ad5dbeca7092/index.js#L31

**Comment by al-bglhk** [comment]
Thank you for the fix! I am hitting the same warning from the logs. When will this fix be released?

**Comment by dougwilson** [comment]
Thanks for this issue, and sorry I was not subscribed to this module's notifications.

I see no issue with reading the new property, but I am a little afraid about modules on npm that are trying to overwrite the ip or mock http may end up having an issue once this is merged.

I am thinking about the impact to the use in Express, so it may extend to other things using this.

So I'm wondering if it would be possible to keep reading both values or something. I will try to research into what the mocks and such are doing at least in the Express ecosystem to assess the impact of switching to a new property, but anyone is welcome to post an assessment as well.

No assessment on the impact has been provided so far, so I will try to do it this weekend since Node.js has deprecated the property used here.

Is the current impact that users of the current Node.js version get warnings or is this just to get it fixed before that happens?

**Comment by silverwind** [comment]
According to https://nodejs.org/api/deprecations.html#deprecations_dep0149_http_incomingmessage_connection it is doc-only deprecation but it did log warnings in 13.0.0 at least.
